spring:
  boot:
    admin:
      notify:
        dingtalk:
          enabled: true
          webhook-token: https://oapi.dingtalk.com/robot/send?access_token=dd98208d71e200900b0a89c917c6532a7e0bbf3d16e67b91bf560f03c21ab2e1
        mail:
          from: zhb923604825@163.com
          to: zhb923604825@163.com
  mail:
    host: smtp.163.com
    username: zhb923604825@163.com
    password: GXUTHXEYWRBAOKZS
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: admin-server
  security:
    user:
      name: admin
      password: 123456
      roles: SBA_ADMIN
server:
  port: 20000

